//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_table()
        {
            this.Tbl_arriving = new HashSet<Tbl_arriving>();
        }
    
        public int id { get; set; }
        public int event_id { get; set; }
        public byte num_of_people { get; set; }
        public bool male { get; set; }
        public string title { get; set; }
        public Nullable<byte> category_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_arriving> Tbl_arriving { get; set; }
        public virtual Tbl_category Tbl_category { get; set; }
        public virtual Tbl_event Tbl_event { get; set; }
    }
}
