//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_arriving
    {
        public int id { get; set; }
        public int guest_id { get; set; }
        public bool male { get; set; }
        public Nullable<int> table_id { get; set; }
    
        public virtual Tbl_guests Tbl_guests { get; set; }
        public virtual Tbl_table Tbl_table { get; set; }
    }
}
