//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_guests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_guests()
        {
            this.Tbl_arriving = new HashSet<Tbl_arriving>();
        }
    
        public int id { get; set; }
        public int id_event { get; set; }
        public string degree_before { get; set; }
        public string degree_after { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public byte category_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_arriving> Tbl_arriving { get; set; }
        public virtual Tbl_category Tbl_category { get; set; }
        public virtual Tbl_event Tbl_event { get; set; }
    }
}
